name: "Git - Commit"
description: "Stage and commit all changes"

inputs:
  message:
    description: "Commit message (supports template variables: {date}, {branch})"
    required: false
    default: "GoUpdate: Update"
  git-user-name:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  git-user-email:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

outputs:
  has-changes:
    description: "Whether any changes were committed"
    value: ${{ steps.commit.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - name: Commit changes
      id: commit
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.message }}
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
      run: |
        set -euo pipefail

        git config user.name "$GIT_USER_NAME"
        git config user.email "$GIT_USER_EMAIL"

        DATE=$(date -u +%Y-%m-%d)
        BRANCH=$(git branch --show-current)
        COMMIT_MESSAGE="${COMMIT_MESSAGE//\{date\}/$DATE}"
        COMMIT_MESSAGE="${COMMIT_MESSAGE//\{branch\}/$BRANCH}"

        if [ -z "$(git status --porcelain)" ]; then
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "No changes to commit"
          exit 0
        fi

        git add -A
        git commit -m "$COMMIT_MESSAGE"

        echo "has_changes=true" >> "$GITHUB_OUTPUT"
