name: "GoUpdate - Scan"
description: "Scan repository for package manager files using goupdate"

inputs:
  working-directory:
    description: "Directory to scan"
    required: false
    default: "."

outputs:
  package-managers:
    description: "Comma-separated list of detected package managers"
    value: ${{ steps.scan.outputs.package_managers }}
  rules:
    description: "Comma-separated list of detected rules"
    value: ${{ steps.scan.outputs.rules }}

runs:
  using: "composite"
  steps:
    - name: Scan
      id: scan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        OUTPUT=$(goupdate scan --output json)

        PMS=$(echo "$OUTPUT" | jq -r '[.files[].pm] | unique | join(",")')
        RULES=$(echo "$OUTPUT" | jq -r '[.files[].rule] | unique | join(",")')

        echo "package_managers=$PMS" >> "$GITHUB_OUTPUT"
        echo "rules=$RULES" >> "$GITHUB_OUTPUT"

        {
          echo "## GoUpdate - Scan"
          echo ""
          echo "- **Package managers:** \`$PMS\`"
          echo "- **Rules:** \`$RULES\`"
          echo ""
          echo "### Files"
          echo "$OUTPUT" | jq -r '.files[] | "- `\(.file)` (\(.rule))"'
        } >> "$GITHUB_STEP_SUMMARY"
