name: "GoUpdate - Update"
description: "Apply dependency updates and create or update branch"

inputs:
  update-type:
    description: "Update type (major, minor, patch)"
    required: false
    default: "minor"
  base-branch:
    description: "Base branch for updates"
    required: true
  branch-prefix:
    description: "Prefix for update branch"
    required: false
    default: "goupdate"
  commit-message:
    description: "Commit message template ({type} and {date} placeholders)"
    required: false
    default: "GoUpdate: {type} update ({date})"

outputs:
  has-changes:
    description: "Whether any changes were made"
    value: ${{ steps.commit.outputs.has_changes }}
  branch-name:
    description: "Name of the update branch"
    value: ${{ steps.branch.outputs.branch_name }}

runs:
  using: "composite"
  steps:
    - name: Setup branch
      id: branch
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        BRANCH_NAME="${{ inputs.branch-prefix }}/auto-update-${{ inputs.update-type }}"
        echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

        git fetch origin "${{ inputs.base-branch }}" "$BRANCH_NAME" 2>/dev/null || git fetch origin "${{ inputs.base-branch }}"

        if git rev-parse --verify "origin/$BRANCH_NAME" >/dev/null 2>&1; then
          echo "Continuing existing branch..."
          git checkout -B "$BRANCH_NAME" "origin/$BRANCH_NAME"
          
          if ! git merge "origin/${{ inputs.base-branch }}" --ff-only 2>/dev/null; then
            echo "::warning::Could not fast-forward merge from ${{ inputs.base-branch }}. Continuing with updates..."
          fi
        else
          echo "Creating new branch..."
          git checkout -B "$BRANCH_NAME" "origin/${{ inputs.base-branch }}"
        fi

    - name: Apply updates
      id: update
      shell: bash
      env:
        BRANCH_NAME: ${{ steps.branch.outputs.branch_name }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        UPDATE_TYPE: ${{ inputs.update-type }}
      run: |
        set -o pipefail
        goupdate update --$UPDATE_TYPE -y --continue-on-fail 2>&1 | tee /tmp/goupdate-output.txt
        EXIT_CODE=$?

        REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"

        {
          echo "## GoUpdate - $UPDATE_TYPE updates"
          echo ""
          echo "- **Base:** [\`$BASE_BRANCH\`]($REPO_URL/tree/$BASE_BRANCH)"
          echo "- **Branch:** [\`$BRANCH_NAME\`]($REPO_URL/tree/$BRANCH_NAME)"
          echo "- **Compare:** [View changes]($REPO_URL/compare/$BASE_BRANCH...$BRANCH_NAME)"
          echo ""
          echo "### Output"
          echo '```'
          cat /tmp/goupdate-output.txt
          echo '```'
        } >> "$GITHUB_STEP_SUMMARY"

        exit $EXIT_CODE

    - name: Commit and push
      id: commit
      shell: bash
      run: |
        if git diff --quiet && git diff --cached --quiet; then
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "No changes to commit"
          exit 0
        fi

        echo "has_changes=true" >> "$GITHUB_OUTPUT"

        DATE=$(date -u +%Y-%m-%d)
        TYPE=$(echo "${{ inputs.update-type }}" | sed 's/\b\(.\)/\u\1/')
        COMMIT_MSG=$(echo "${{ inputs.commit-message }}" | sed "s/{date}/$DATE/g" | sed "s/{type}/$TYPE/g")

        git add -A
        git commit -m "$COMMIT_MSG"
        git push -u origin "${{ steps.branch.outputs.branch_name }}" --force-with-lease
