name: "GoUpdate - Update"
description: "Apply dependency updates (does not handle branch setup or commits — use git/checkout and git/commit)"

inputs:
  update-type:
    description: "Update type (major, minor, patch)"
    required: false
    default: "minor"

outputs:
  has-changes:
    description: "Whether any changes were produced"
    value: ${{ steps.results.outputs.has_changes }}
  partial-failure:
    description: "Whether some updates failed (true if exit code != 0 but changes exist)"
    value: ${{ steps.results.outputs.partial_failure }}

runs:
  using: "composite"
  steps:
    - name: Apply updates
      id: update
      shell: bash
      env:
        UPDATE_TYPE: ${{ inputs.update-type }}
      run: |
        set -uo pipefail

        goupdate update --"$UPDATE_TYPE" -y --continue-on-fail 2>&1 | tee /tmp/goupdate-output.txt
        EXIT_CODE=${PIPESTATUS[0]}

        echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

        {
          echo "## GoUpdate - $UPDATE_TYPE"
          echo ""
          echo '```'
          cat /tmp/goupdate-output.txt
          echo '```'
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Check results
      id: results
      shell: bash
      env:
        UPDATE_EXIT_CODE: ${{ steps.update.outputs.exit_code }}
      run: |
        set -euo pipefail

        if [ -z "$(git status --porcelain)" ]; then
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "partial_failure=false" >> "$GITHUB_OUTPUT"

          if [ "$UPDATE_EXIT_CODE" != "0" ]; then
            echo "::error::All updates failed with no changes produced. Check goupdate output above."
            exit 1
          fi

          echo "No changes detected"
          exit 0
        fi

        echo "has_changes=true" >> "$GITHUB_OUTPUT"

        if [ "$UPDATE_EXIT_CODE" != "0" ]; then
          echo "partial_failure=true" >> "$GITHUB_OUTPUT"
          echo "::warning::Some updates failed (exit code $UPDATE_EXIT_CODE) but changes exist"
        else
          echo "partial_failure=false" >> "$GITHUB_OUTPUT"
        fi
