name: "GoUpdate - Outdated"
description: "Check for outdated packages using goupdate"

inputs:
  working-directory:
    description: "Directory to check"
    required: false
    default: "."

outputs:
  total:
    description: "Total number of packages"
    value: ${{ steps.outdated.outputs.total }}
  total-outdated:
    description: "Total number of outdated packages"
    value: ${{ steps.outdated.outputs.total_outdated }}
  major:
    description: "Number of major updates"
    value: ${{ steps.outdated.outputs.major }}
  minor:
    description: "Number of minor updates"
    value: ${{ steps.outdated.outputs.minor }}
  patch:
    description: "Number of patch updates"
    value: ${{ steps.outdated.outputs.patch }}

runs:
  using: "composite"
  steps:
    - name: Check outdated
      id: outdated
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        OUTPUT=$(goupdate outdated --output json)

        TOTAL=$(echo "$OUTPUT" | jq '.summary.total_packages // 0')
        OUTDATED=$(echo "$OUTPUT" | jq '.summary.outdated_packages // 0')
        MAJOR=$(echo "$OUTPUT" | jq '.summary.has_major // 0')
        MINOR=$(echo "$OUTPUT" | jq '.summary.has_minor // 0')
        PATCH=$(echo "$OUTPUT" | jq '.summary.has_patch // 0')

        echo "total=$TOTAL" >> "$GITHUB_OUTPUT"
        echo "total_outdated=$OUTDATED" >> "$GITHUB_OUTPUT"
        echo "major=$MAJOR" >> "$GITHUB_OUTPUT"
        echo "minor=$MINOR" >> "$GITHUB_OUTPUT"
        echo "patch=$PATCH" >> "$GITHUB_OUTPUT"

        {
          echo "## GoUpdate - Outdated"
          echo ""
          echo "- **Total packages:** $TOTAL"
          echo "- **Outdated:** $OUTDATED (major: $MAJOR, minor: $MINOR, patch: $PATCH)"
          echo ""
          
          MAJOR_PKGS=$(echo "$OUTPUT" | jq -r '.packages[] | select(.major != "#N/A") | "- `\(.name)`"')
          MINOR_PKGS=$(echo "$OUTPUT" | jq -r '.packages[] | select(.minor != "#N/A") | "- `\(.name)`"')
          PATCH_PKGS=$(echo "$OUTPUT" | jq -r '.packages[] | select(.patch != "#N/A") | "- `\(.name)`"')
          UPTODATE_PKGS=$(echo "$OUTPUT" | jq -r '.packages[] | select(.status == "UpToDate") | "- `\(.name)`"')
          
          if [ -n "$MAJOR_PKGS" ]; then
            echo "### Major"
            echo "$MAJOR_PKGS"
            echo ""
          fi
          
          if [ -n "$MINOR_PKGS" ]; then
            echo "### Minor"
            echo "$MINOR_PKGS"
            echo ""
          fi
          
          if [ -n "$PATCH_PKGS" ]; then
            echo "### Patch"
            echo "$PATCH_PKGS"
            echo ""
          fi
          
          if [ -n "$UPTODATE_PKGS" ]; then
            echo "### Up to date"
            echo "$UPTODATE_PKGS"
          fi
        } >> "$GITHUB_STEP_SUMMARY"
