name: "JS - Install"
description: "Install and cache Node.js dependencies"

inputs:
  working-directory:
    description: "Directory containing package.json"
    required: false
    default: "."
  package-manager:
    description: "Package manager (npm, yarn, pnpm). Auto-detects if not set."
    required: false
    default: ""

outputs:
  package-manager:
    description: "Detected or specified package manager"
    value: ${{ steps.detect.outputs.pm }}
  cache-hit:
    description: "Whether cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Detect package manager
      id: detect
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        PM="${{ inputs.package-manager }}"

        if [ -n "$PM" ]; then
          if [[ ! "$PM" =~ ^(npm|yarn|pnpm)$ ]]; then
            echo "::error::Invalid package manager '$PM'. Must be npm, yarn, or pnpm."
            exit 1
          fi
          echo "pm=$PM" >> "$GITHUB_OUTPUT"
        elif [ -f "pnpm-lock.yaml" ]; then
          echo "pm=pnpm" >> "$GITHUB_OUTPUT"
        elif [ -f "yarn.lock" ]; then
          echo "pm=yarn" >> "$GITHUB_OUTPUT"
        elif [ -f "package-lock.json" ]; then
          echo "pm=npm" >> "$GITHUB_OUTPUT"
        else
          echo "::error::No lock file found"
          exit 1
        fi

    - name: Cache node_modules
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-directory }}/node_modules
          ${{ inputs.working-directory }}/**/node_modules
        key: ${{ runner.os }}-node_modules-${{ steps.detect.outputs.pm }}-${{ hashFiles(format('{0}/*-lock.*', inputs.working-directory), format('{0}/yarn.lock', inputs.working-directory)) }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        PM="${{ steps.detect.outputs.pm }}"
        if ! command -v "$PM" &>/dev/null; then
          echo "::error::$PM not found. Run github/runtimes first."
          exit 1
        fi
        case "$PM" in
          pnpm) pnpm install --frozen-lockfile ;;
          yarn) yarn install --immutable ;;
          npm)  npm ci ;;
        esac
