name: "GitHub - PR"
description: "Create or update a pull request. Updates title and body on existing PRs"

inputs:
  app-id:
    description: "GitHub App ID"
    required: false
    default: ""
  app-private-key:
    description: "GitHub App private key"
    required: false
    default: ""
  github-token:
    description: "GitHub token (fallback when GitHub App not provided)"
    required: false
    default: ""
  title:
    description: "PR title (supports template variables: {date}, {base}, {head})"
    required: true
  body:
    description: "PR body (supports template variables: {date}, {base}, {head})"
    required: false
    default: ""
  base:
    description: "Base branch"
    required: true
  head:
    description: "Head branch"
    required: true

outputs:
  pr-number:
    description: "PR number"
    value: ${{ steps.pr.outputs.number }}
  pr-url:
    description: "PR URL"
    value: ${{ steps.pr.outputs.url }}
  created:
    description: "Whether PR was created (false if already existed)"
    value: ${{ steps.pr.outputs.created }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      id: validate
      shell: bash
      env:
        APP_ID: ${{ inputs.app-id }}
        APP_PRIVATE_KEY: ${{ inputs.app-private-key }}
        GH_TOKEN_INPUT: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        if [ -n "$APP_ID" ] && [ -n "$APP_PRIVATE_KEY" ]; then
          echo "auth=app" >> "$GITHUB_OUTPUT"
        elif [ -n "$GH_TOKEN_INPUT" ]; then
          echo "auth=token" >> "$GITHUB_OUTPUT"
        else
          echo "::error::Either app-id + app-private-key or github-token must be provided"
          exit 1
        fi

    - name: Generate app token
      id: app-token
      if: steps.validate.outputs.auth == 'app'
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}

    - name: Set token
      id: token
      shell: bash
      env:
        APP_TOKEN: ${{ steps.app-token.outputs.token }}
        GH_TOKEN_INPUT: ${{ inputs.github-token }}
        AUTH: ${{ steps.validate.outputs.auth }}
      run: |
        set -euo pipefail

        if [ "$AUTH" = "app" ]; then
          TOKEN="$APP_TOKEN"
        else
          TOKEN="$GH_TOKEN_INPUT"
        fi

        echo "::add-mask::$TOKEN"
        echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

    - name: Create or find PR
      id: pr
      shell: bash
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
        TITLE: ${{ inputs.title }}
        BODY: ${{ inputs.body }}
        BASE: ${{ inputs.base }}
        HEAD: ${{ inputs.head }}
      run: |
        set -euo pipefail

        DATE=$(date -u +%Y-%m-%d)
        TITLE="${TITLE//\{date\}/$DATE}"
        TITLE="${TITLE//\{base\}/$BASE}"
        TITLE="${TITLE//\{head\}/$HEAD}"
        BODY="${BODY//\{date\}/$DATE}"
        BODY="${BODY//\{base\}/$BASE}"
        BODY="${BODY//\{head\}/$HEAD}"

        EXISTING=$(gh pr list --head "$HEAD" --base "$BASE" --json number,url --jq '.[0] // empty')

        if [ -n "$EXISTING" ]; then
          PR_NUMBER=$(echo "$EXISTING" | jq -r '.number')
          PR_URL=$(echo "$EXISTING" | jq -r '.url')

          gh pr edit "$PR_NUMBER" --title "$TITLE" --body "$BODY"

          echo "number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "url=$PR_URL" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          echo "PR already exists (updated): $PR_URL"
        else
          PR_URL=$(gh pr create --title "$TITLE" --body "$BODY" --base "$BASE" --head "$HEAD")
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

          echo "number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "url=$PR_URL" >> "$GITHUB_OUTPUT"
          echo "created=true" >> "$GITHUB_OUTPUT"
        fi

